on: push

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm install
          npm run build
          npm run package
          rm -rf node_modules index.js
      - uses: ./
      - uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          message: automated build
          add: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
