on: push

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install, build, package
        run: |
          npm install
          npm run build
          npm run package
          rm -rf node_modules index.js

      - name: Test action runs
        id: test
        uses: ./

      - name: Test action outputs NODE_VERSION
        if: ${{ steps.test.outputs.NODE_VERSION }} == "12.x"
        run: echo "Successfully read NODE_VERSION"

      - name: Test action outputs APP_ENV
        if: ${{ steps.test.outputs.APP_ENV }} == "prod"
        run: echo "Successfully loaded .env.prod and set APP_ENV=prod output"

      - name: Commit newly built/packaged action
        uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          message: automated build
          add: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
